name: Generate Java test results

on:
  workflow_call:
    outputs:
      test-results:
        description: An array of the test results
        value: ${{ jobs.java-test.outputs.test_results }}

jobs:
  java-test:
    runs-on: ubuntu-24.04
    timeout-minutes: 2

    outputs:
      test_results: ${{ steps.get-results.outputs.test_results }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build & test
        continue-on-error: true # we don't wanna stress the test takers with errors
        run: mvn test

      - name: Output test results
        id: get-results
        run: |
          echo test_results=$(
            cat $(find ./target/surefire-reports/*.xml -print -quit) | 
            yq -p=xml -o=json '[ 
              .. | select(has("testcase")) | .testcase[] | ( # we traverse the whole xml recursively since "testcase" can be nested
                with(select(length > 3); # if the item has extra children (eg. 'failure' or 'error'), tag it as failed
                  .result = "failed"
                ) |
                with(select(length <= 3); # if the item has no extra children, tag it as passed
                  .result = "passed"
                )
              ) | { "test": .+@name, "result": .result }
            ]' 
          ) | sed 's/"/\\"/g' >> $GITHUB_OUTPUT
