name: Generates JavaScript test results

on:
  workflow_call:
    inputs:
      test-file-pattern:
        type: string
        description: The file pattern for the test files
        default: '**/*.test.js'
    outputs:
      test-results:
        description: An array of the test results
        value: ${{ jobs.javascript-test.outputs.test_results }}

jobs:
  javascript-test:
    runs-on: ubuntu-24.04
    timeout-minutes: 2

    outputs:
      test_results: ${{ steps.get-results.outputs.test_results }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        continue-on-error: true # we don't wanna stress the test takers with errors
        run: node --test --test-reporter=junit --test-reporter-destination=test-results.xml ${{ inputs.test-file-pattern }}

      - name: Send test results to output
        id: get-results
        run: |
          echo test_results=$(
            cat $(find ./test-results.xml -print -quit) | 
            yq -p=xml -o=json '[ 
              .. | select(has("testcase")) | .testcase[] | ( # we traverse the whole xml recursively since "testcase" can be nested
                with(select(length > 3); # if the item has extra children (eg. 'failure' or 'error'), tag it as failed
                  .result = "failed"
                ) |
                with(select(length <= 3); # if the item has no extra children, tag it as passed
                  .result = "passed"
                )
              ) | { "test": .+@name, "result": .result }
            ]' 
          ) | sed 's/"/\\"/g' >> $GITHUB_OUTPUT
