name: Generates .NET test results

on:
  workflow_call:
    outputs:
      test-results:
        description: An array of the test results
        value: ${{ jobs.dotnet-test.outputs.test_results }}

jobs:
  dotnet-test:
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    continue-on-error: true # We expect this job to fail, but still need the results to be published

    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    outputs:
      test_results: ${{ steps.get-results.outputs.test_results }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Build & test
        run: dotnet test --nologo -v:q --logger trx --logger GitHubActions

      - name: Output test results
        id: get-results
        if: ${{ !cancelled() }}
        run: |
          echo test_results=$(
            cat $(find ./TestResults/*.trx -print -quit) |
            yq -p=xml -o=json '[ .TestRun.Results.UnitTestResult[] | { "test": .+@testName, "result": .+@outcome } ]'
          ) >> $GITHUB_OUTPUT

      - name: Save cache
        if: ${{ !cancelled() && steps.cache-restore.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
