name: Generates JavaScript test results

on:
  workflow_call:
    inputs:
      test-file-pattern:
        type: string
        description: The file pattern for the test files
        default: '**/*.test.js'
    outputs:
      test-results:
        description: An array of the test results
        value: ${{ jobs.javascript-test.outputs.test_results }}

jobs:
  javascript-test:
    runs-on: ubuntu-24.04
    timeout-minutes: 2

    outputs:
      test_results: ${{ steps.get-results.outputs.test_results }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Run tests
        continue-on-error: true
        run: node --test --test-reporter=./utils/json-reporter.js --test-reporter-destination=test-results-raw.json ${{ inputs.test-file-pattern }}
          
      - name: Escape double quotes in the json-file
        run: sed 's/"/\\"/g' test-results-raw.json > test-results-parsed.json

      - name: Send test results to output
        id: get-results
        run: echo test_results=$(cat ./test-results-parsed.json) >> $GITHUB_OUTPUT
